# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6a1cd9cee4b0e58d5dcd5bb0aae4c8a57a8385fd0b76a7c6c8a59f04e0377644eca35c8227e2daf4719726f32e165529fbb57c2474863fb696558f79c67de53

test:
  secret_key_base: 817e53ef3afe73d8f61cbbc9e8226d6115983d12e8512832c1cb27a026ca7a5e2b15e1b9b9a130a4db7a1e9284bc6ca3a04bdb08c54985d039526186444b2d8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
